-- Phase F7: add a generic app_config key-value table for global flags.
--
-- First user is the billing toggle (key="billing_enabled"). Future global
-- flags (e.g. maintenance_mode, feature_x_enabled) can reuse the same
-- table with a different key.
--
-- Purely additive: new table only, no DROP / ALTER on existing tables, so
-- this is safe to apply against the production Supabase even though
-- preview and prod share the same database (CLAUDE.md lesson #6).
--
-- The default behaviour with the table empty matches the pre-F7 state:
-- billingGate middleware reads "missing row" as flag=false → app stays
-- free for everyone until the toggle is flipped via the owner-only
-- admin endpoint.
--
-- `id` is `TEXT NOT NULL` with no SQL default because @default(cuid())
-- is generated by Prisma client at insert time, not by Postgres.
-- `updatedAt` has no SQL default for the same reason — Prisma manages
-- the column on every update at the application layer.

-- CreateTable
CREATE TABLE "app_config" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "app_config_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "app_config_key_key" ON "app_config"("key");
