export type Country = {
  code: string;        // ISO 3166-1 alpha-2 (lowercase, used for flagcdn)
  name: string;        // Display name
  currency: string;    // ISO 4217 code
  symbol: string;      // Currency symbol
};

// Curated list matching CountrySelector's 90+ markets.
export const COUNTRIES: Country[] = [
  { code: "af", name: "Afghanistan",         currency: "AFN", symbol: "؋" },
  { code: "al", name: "Albania",             currency: "EUR", symbol: "€" },
  { code: "dz", name: "Algeria",             currency: "DZD", symbol: "د.ج" },
  { code: "ad", name: "Andorra",             currency: "EUR", symbol: "€" },
  { code: "ao", name: "Angola",              currency: "USD", symbol: "$" },
  { code: "ag", name: "Antigua & Barbuda",   currency: "XCD", symbol: "$" },
  { code: "ar", name: "Argentina",           currency: "USD", symbol: "$" },
  { code: "am", name: "Armenia",             currency: "AMD", symbol: "֏" },
  { code: "aw", name: "Aruba",               currency: "AWG", symbol: "ƒ" },
  { code: "au", name: "Australia",           currency: "AUD", symbol: "$" },
  { code: "at", name: "Austria",             currency: "EUR", symbol: "€" },
  { code: "az", name: "Azerbaijan",          currency: "AZN", symbol: "₼" },
  { code: "bs", name: "Bahamas",             currency: "BSD", symbol: "$" },
  { code: "bh", name: "Bahrain",             currency: "USD", symbol: "$" },
  { code: "bd", name: "Bangladesh",          currency: "BDT", symbol: "৳" },
  { code: "bb", name: "Barbados",            currency: "BBD", symbol: "$" },
  { code: "by", name: "Belarus",             currency: "EUR", symbol: "€" },
  { code: "be", name: "Belgium",             currency: "EUR", symbol: "€" },
  { code: "bz", name: "Belize",              currency: "BZD", symbol: "$" },
  { code: "bj", name: "Benin",               currency: "XOF", symbol: "FR" },
  { code: "bm", name: "Bermuda",             currency: "USD", symbol: "$" },
  { code: "bt", name: "Bhutan",              currency: "USD", symbol: "$" },
  { code: "bo", name: "Bolivia",             currency: "BOB", symbol: "Bs." },
  { code: "ba", name: "Bosnia & Herzegovina",currency: "EUR", symbol: "€" },
  { code: "bw", name: "Botswana",            currency: "BWP", symbol: "P" },
  { code: "br", name: "Brazil",              currency: "USD", symbol: "$" },
  { code: "bn", name: "Brunei",              currency: "BND", symbol: "$" },
  { code: "bg", name: "Bulgaria",            currency: "EUR", symbol: "€" },
  { code: "kh", name: "Cambodia",            currency: "KHR", symbol: "៛" },
  { code: "cm", name: "Cameroon",            currency: "XAF", symbol: "CFA" },
  { code: "ca", name: "Canada",              currency: "CAD", symbol: "$" },
  { code: "cv", name: "Cape Verde",          currency: "CVE", symbol: "$" },
  { code: "ky", name: "Cayman Islands",      currency: "KYD", symbol: "$" },
  { code: "td", name: "Chad",                currency: "XAF", symbol: "CFA" },
  { code: "cl", name: "Chile",               currency: "USD", symbol: "$" },
  { code: "cn", name: "China",               currency: "CNY", symbol: "¥" },
  { code: "co", name: "Colombia",            currency: "USD", symbol: "$" },
  { code: "cr", name: "Costa Rica",          currency: "CRC", symbol: "₡" },
  { code: "hr", name: "Croatia",             currency: "EUR", symbol: "€" },
  { code: "cy", name: "Cyprus",              currency: "EUR", symbol: "€" },
  { code: "cz", name: "Czech Republic",      currency: "CZK", symbol: "Kč" },
  { code: "dk", name: "Denmark",             currency: "DKK", symbol: "kr" },
  { code: "do", name: "Dominican Republic",  currency: "DOP", symbol: "$" },
  { code: "ec", name: "Ecuador",             currency: "USD", symbol: "$" },
  { code: "eg", name: "Egypt",               currency: "EGP", symbol: "£" },
  { code: "ee", name: "Estonia",             currency: "EUR", symbol: "€" },
  { code: "et", name: "Ethiopia",            currency: "ETB", symbol: "Br" },
  { code: "fj", name: "Fiji",                currency: "FJD", symbol: "$" },
  { code: "fi", name: "Finland",             currency: "EUR", symbol: "€" },
  { code: "fr", name: "France",              currency: "EUR", symbol: "€" },
  { code: "ge", name: "Georgia",             currency: "GEL", symbol: "₾" },
  { code: "de", name: "Germany",             currency: "EUR", symbol: "€" },
  { code: "gh", name: "Ghana",               currency: "GHS", symbol: "₵" },
  { code: "gr", name: "Greece",              currency: "EUR", symbol: "€" },
  { code: "gt", name: "Guatemala",           currency: "GTQ", symbol: "Q" },
  { code: "hk", name: "Hong Kong SAR",       currency: "HKD", symbol: "$" },
  { code: "hu", name: "Hungary",             currency: "HUF", symbol: "Ft" },
  { code: "is", name: "Iceland",             currency: "ISK", symbol: "kr" },
  { code: "in", name: "India",               currency: "INR", symbol: "₹" },
  { code: "id", name: "Indonesia",           currency: "IDR", symbol: "Rp" },
  { code: "ie", name: "Ireland",             currency: "EUR", symbol: "€" },
  { code: "il", name: "Israel",              currency: "ILS", symbol: "₪" },
  { code: "it", name: "Italy",               currency: "EUR", symbol: "€" },
  { code: "jm", name: "Jamaica",             currency: "BBD", symbol: "$" },
  { code: "jp", name: "Japan",               currency: "JPY", symbol: "¥" },
  { code: "jo", name: "Jordan",              currency: "JOD", symbol: "د.أ" },
  { code: "kz", name: "Kazakhstan",          currency: "KZT", symbol: "₸" },
  { code: "ke", name: "Kenya",               currency: "KES", symbol: "KSh" },
  { code: "kw", name: "Kuwait",              currency: "USD", symbol: "$" },
  { code: "lv", name: "Latvia",              currency: "EUR", symbol: "€" },
  { code: "lb", name: "Lebanon",             currency: "LBP", symbol: "ل.ل" },
  { code: "lt", name: "Lithuania",           currency: "EUR", symbol: "€" },
  { code: "lu", name: "Luxembourg",          currency: "EUR", symbol: "€" },
  { code: "mo", name: "Macao SAR",           currency: "MOP", symbol: "P" },
  { code: "my", name: "Malaysia",            currency: "MYR", symbol: "RM" },
  { code: "mv", name: "Maldives",            currency: "MVR", symbol: "Rf" },
  { code: "mt", name: "Malta",               currency: "EUR", symbol: "€" },
  { code: "mu", name: "Mauritius",           currency: "MUR", symbol: "₨" },
  { code: "mx", name: "Mexico",              currency: "MXN", symbol: "$" },
  { code: "mc", name: "Monaco",              currency: "EUR", symbol: "€" },
  { code: "ma", name: "Morocco",             currency: "MAD", symbol: "د.م" },
  { code: "mm", name: "Myanmar",             currency: "MMK", symbol: "K" },
  { code: "np", name: "Nepal",               currency: "NPR", symbol: "₨" },
  { code: "nl", name: "Netherlands",         currency: "EUR", symbol: "€" },
  { code: "nz", name: "New Zealand",         currency: "NZD", symbol: "$" },
  { code: "ng", name: "Nigeria",             currency: "NGN", symbol: "₦" },
  { code: "no", name: "Norway",              currency: "NOK", symbol: "kr" },
  { code: "om", name: "Oman",                currency: "OMR", symbol: "ر.ع" },
  { code: "pk", name: "Pakistan",            currency: "PKR", symbol: "₨" },
  { code: "pa", name: "Panama",              currency: "USD", symbol: "$" },
  { code: "py", name: "Paraguay",            currency: "PYG", symbol: "₲" },
  { code: "pe", name: "Peru",                currency: "PEN", symbol: "S/" },
  { code: "ph", name: "Philippines",         currency: "PHP", symbol: "₱" },
  { code: "pl", name: "Poland",              currency: "PLN", symbol: "zł" },
  { code: "pt", name: "Portugal",            currency: "EUR", symbol: "€" },
  { code: "qa", name: "Qatar",               currency: "QAR", symbol: "ر.ق" },
  { code: "ro", name: "Romania",             currency: "RON", symbol: "lei" },
  { code: "rw", name: "Rwanda",              currency: "RWF", symbol: "FRw" },
  { code: "sa", name: "Saudi Arabia",        currency: "SAR", symbol: "ر.س" },
  { code: "rs", name: "Serbia",              currency: "RSD", symbol: "дин" },
  { code: "sg", name: "Singapore",           currency: "SGD", symbol: "$" },
  { code: "sk", name: "Slovakia",            currency: "EUR", symbol: "€" },
  { code: "si", name: "Slovenia",            currency: "EUR", symbol: "€" },
  { code: "za", name: "South Africa",        currency: "ZAR", symbol: "R" },
  { code: "kr", name: "South Korea",         currency: "KRW", symbol: "₩" },
  { code: "es", name: "Spain",               currency: "EUR", symbol: "€" },
  { code: "lk", name: "Sri Lanka",           currency: "LKR", symbol: "₨" },
  { code: "se", name: "Sweden",              currency: "SEK", symbol: "kr" },
  { code: "ch", name: "Switzerland",         currency: "CHF", symbol: "CHF" },
  { code: "tw", name: "Taiwan",              currency: "TWD", symbol: "$" },
  { code: "tz", name: "Tanzania",            currency: "TZS", symbol: "TSh" },
  { code: "th", name: "Thailand",            currency: "THB", symbol: "฿" },
  { code: "tt", name: "Trinidad & Tobago",   currency: "TTD", symbol: "$" },
  { code: "tn", name: "Tunisia",             currency: "TND", symbol: "د.ت" },
  { code: "tr", name: "Turkey",              currency: "TRY", symbol: "₺" },
  { code: "ug", name: "Uganda",              currency: "UGX", symbol: "USh" },
  { code: "ua", name: "Ukraine",             currency: "UAH", symbol: "₴" },
  { code: "ae", name: "United Arab Emirates",currency: "AED", symbol: "د.إ" },
  { code: "gb", name: "United Kingdom",      currency: "GBP", symbol: "£" },
  { code: "us", name: "United States",       currency: "USD", symbol: "$" },
  { code: "uy", name: "Uruguay",             currency: "UYU", symbol: "$" },
  { code: "uz", name: "Uzbekistan",          currency: "UZS", symbol: "сўм" },
  { code: "ve", name: "Venezuela",           currency: "USD", symbol: "$" },
  { code: "vn", name: "Vietnam",             currency: "VND", symbol: "₫" },
  { code: "ye", name: "Yemen",               currency: "YER", symbol: "ر.ي" },
  { code: "zm", name: "Zambia",              currency: "USD", symbol: "$" },
  { code: "zw", name: "Zimbabwe",            currency: "USD", symbol: "$" },
];

export const STORAGE_KEY = "estrella:selectedCountryCode";
export const DEFAULT_CODE = "us";

export const DEFAULT_RATES: Record<string, number> = {
  USD: 1.0,
  INR: 83.5,
  EUR: 0.92,
  GBP: 0.79,
  CAD: 1.37,
  AUD: 1.51,
  SGD: 1.35,
  AED: 3.67,
  SAR: 3.75,
  CNY: 7.24,
  JPY: 156.0,
  HKD: 7.82,
  CHF: 0.91,
};

export async function fetchExchangeRates(): Promise<Record<string, number>> {
  try {
    const res = await fetch("https://open.er-api.com/v6/latest/USD");
    if (!res.ok) throw new Error("Failed to fetch exchange rates");
    const data = await res.json();
    if (data && data.result === "success" && data.rates) {
      return data.rates;
    }
  } catch (err) {
    console.warn("Exchange rate fetch failed, using default rates:", err);
  }
  return DEFAULT_RATES;
}
